import { DiagnosticSession } from '../types';
import { ScoringEngine } from './ScoringEngine';
import * as Sharing from 'expo-sharing';

export class ReportGenerator {
  private scoringEngine: ScoringEngine;

  constructor() {
    this.scoringEngine = new ScoringEngine();
  }

  async generateTextReport(session: DiagnosticSession): Promise<string> {
    const counts = this.scoringEngine.getStatusCounts(session.results);
    const scoreLabel = this.scoringEngine.getScoreLabel(session.healthScore);

    let report = '═══════════════════════════════════════\n';
    report += '     DEVICE DIAGNOSTIC REPORT\n';
    report += '═══════════════════════════════════════\n\n';

    report += 'DEVICE INFORMATION\n';
    report += '─────────────────\n';
    report += `Model:          ${session.deviceModel || 'Unknown'}\n`;
    report += `Manufacturer:   ${session.deviceManufacturer || 'Unknown'}\n`;
    report += `OS Version:     ${session.osVersion || 'Unknown'}\n`;
    report += `Date:           ${new Date(session.timestamp).toLocaleString()}\n`;
    report += `Duration:       ${(session.duration / 1000).toFixed(1)}s\n\n`;

    report += 'OVERALL HEALTH SCORE\n';
    report += '─────────────────\n';
    report += `Score: ${session.healthScore}/100 (${scoreLabel})\n\n`;

    report += 'TEST SUMMARY\n';
    report += '─────────────────\n';
    report += `  Passed:            ${counts.pass}\n`;
    report += `  Warnings:          ${counts.warning}\n`;
    report += `  Failed:            ${counts.fail}\n`;
    report += `  Not Supported:     ${counts.notSupported}\n`;
    report += `  Not Tested:        ${counts.notTested}\n\n`;

    report += 'DETAILED RESULTS\n';
    report += '═══════════════════════════════════════\n\n';

    const categories = [...new Set(session.results.map(r => r.category))];
    for (const category of categories) {
      const categoryResults = session.results.filter(r => r.category === category);
      report += `> ${category.toUpperCase()}\n`;
      report += '─────────────────\n';

      for (const result of categoryResults) {
        const icon = this.getStatusIcon(result.status);
        report += `  ${icon} ${result.testName}: ${result.status}\n`;
        report += `    ${result.message}\n`;

        const detailEntries = Object.entries(result.details);
        if (detailEntries.length > 0) {
          for (const [key, value] of detailEntries) {
            report += `      ${key}: ${value}\n`;
          }
        }
        report += '\n';
      }
    }

    report += '═══════════════════════════════════════\n';
    report += 'Generated by MAC Diagnostic Center\n';
    report += 'All data is stored locally on this device.\n';

    return report;
  }

  async shareReport(session: DiagnosticSession): Promise<void> {
    const report = await this.generateTextReport(session);
    const available = await Sharing.isAvailableAsync();
    if (available) {
      const encoded = encodeURIComponent(report);
      await Sharing.shareAsync(`data:text/plain;charset=utf-8,${encoded}`, {
        mimeType: 'text/plain',
        dialogTitle: 'Share Diagnostic Report',
      });
    }
  }

  private getStatusIcon(status: string): string {
    switch (status) {
      case 'PASS': return 'OK';
      case 'WARNING': return '!!';
      case 'FAIL': return 'XX';
      case 'NOT_SUPPORTED': return '--';
      case 'NOT_TESTED': return '??';
      default: return 'OO';
    }
  }
}
